#version: '3.8'
#services:
#  mysql:
#    image: mysql:latest
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: 12345
#      MYSQL_DATABASE: easy_lend
#      MYSQL_USER: may
#      MYSQL_PASSWORD: 12345
#    volumes:
#      - mysql_data:/var/lib/mysql
#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - 6379:6379
#    volumes:
#      - redis_data:/data
#
#volumes:
#  mysql_data:
#  redis_data:
