#RabbitMQ
spring:
  rabbitmq:
    host: 2.tcp.eu.ngrok.io
    port: 10174
    username: guest
    password: guest
    dynamic: true

  # MySQL connection
  security:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/profile_mgt?allowPublicKeyRetrieval=true
    username: root
    password: Bongo@501
  jpa:
    spring:
      jpa:
        database-platform=org:
          hibernate:
            dialect:
              MySQL8Dialect:

    hibernate:
      ddl-auto: create
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#Cloudinary
  cloudinary:
    cloud_name: dqqlpmdpm
    api_key: 967725158739296
    api_secret: WzXnPmgukKQXG6BxkQuPxMhuxYU
    spring:
      servlet:
        multipart:
          max-file-size=3MB:

#JWT secret from user-mgt-service
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

#Swagger
  swagger:
    version: 1.0.0