# MySQL connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profile_mgt?allowPublicKeyRetrieval=true
    username: root
    password: Bongo@501
  jpa:
    spring:
      jpa:
        database-platform=org:
          hibernate:
            dialect:
              MySQL8Dialect:

    hibernate:
      ddl-auto: create
    show-sql: true


#Cloudinary
cloudinary:
  cloud_name: dqqlpmdpm
  api_key: 967725158739296
  api_secret: WzXnPmgukKQXG6BxkQuPxMhuxYU


# RabbitMQ settings
rabbitmq:
  host: localhost
  virtualhost: /
  port: 15672
  username: guest
  password: guest
  exchange: profile-exchange

  # Queue for profile creation
  createProfileQueue: create-profile
  createProfileRoutingKey: profile-routingkey

  # Queues for screen updates
  updateContactInformationQueue: update-contact-information
  updateContactInformationRoutingKey: contact-information-routingkey

  updateEmploymentStatusQueue: update-employment-status
  updateEmploymentStatusRoutingKey: employment-status-routingkey

  updateGovernmentIDQueue: update-government-id
  updateGovernmentIDRoutingKey: government-id-routingkey

  updateIncomeStatusQueue: update-income-status
  updateIncomeStatusRoutingKey: income-status-routingkey

  updateBankAccountQueue: update-bank-account
  updateBankAccountRoutingKey: bank-account-routingkey

  updateProofOfAddressQueue: update-proof-of-address
  updateProofOfAddressRoutingKey: proof-of-address-routingkey

  reply:
    timeout: 60000
  concurrent:
    consumers: 1
  max:
    concurrent:
      consumers: 1
