# MySQL connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profile_mgt?allowPublicKeyRetrieval=true
    username: root
    password: Bongo@501
  jpa:
    spring:
      jpa:
        database-platform=org:
          hibernate:
            dialect:
              MySQL8Dialect:

    hibernate:
      ddl-auto: create
    show-sql: true


#Cloudinary
cloudinary:
  cloud_name: dqqlpmdpm
  api_key: 967725158739296
  api_secret: WzXnPmgukKQXG6BxkQuPxMhuxYU


#RabbitMQ settings
rabbitmq:
  host: localhost
  virtualhost: /
  port: 15672
  username: guest
  password: guest
  exchange: work-item-exchange
  queue: work-items
  routingkey: work-item-routingkey
  reply:
    timeout: 60000
  concurrent:
    consumers: 1
  max:
    concurrent:
      consumers: 1