# MySQL connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profile_mgt?allowPublicKeyRetrieval=true
    username: root
    password: Bongo@501
  jpa:
    spring:
      jpa:
        database-platform=org:
          hibernate:
            dialect:
              MySQL8Dialect:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


    hibernate:
      ddl-auto: create
    show-sql: true


#Cloudinary
cloudinary:
  cloud_name: dqqlpmdpm
  api_key: 967725158739296
  api_secret: WzXnPmgukKQXG6BxkQuPxMhuxYU
  spring:
    servlet:
      multipart:
        max-file-size=3MB:


#RabbitMQ settings
rabbitmq:
  host: localhost
  virtualhost: /
  port: 15672
  username: guest
  password: guest
  exchange: rabbitmq.exchange
  queue: profile.queue
  routingkey: rabbitmq.routingkey
  reply:
    timeout: 60000
  concurrent:
    consumers: 1
  max:
    concurrent:
      consumers: 1

#JWT secret from user-mgt-service
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Enable Swagger UI
springfox:
  documentation:
    swagger-ui:
      enabled: true
swagger:
  version: 1.0.0